"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteInventoryController = exports.listInventoryController = exports.createInventoryController = void 0;
var CreateInventoryController_1 = require("./controllers/CreateInventoryController");
var DeleteInventoryUseCases_1 = require("../application/useCases/DeleteInventoryUseCases");
var ListInventoryUseCases_1 = require("../application/useCases/ListInventoryUseCases");
var CreateInventoryUseCases_1 = require("./../application/useCases/CreateInventoryUseCases");
var ListInventoryController_1 = require("./controllers/ListInventoryController");
var DeleteInventoryController_1 = require("./controllers/DeleteInventoryController");
var MysqlInventoryRepository_1 = require("./repositories/MysqlInventoryRepository");
var DecreaseSoldStockUseCases_1 = require("../application/useCases/DecreaseSoldStockUseCases");
var database = new MysqlInventoryRepository_1.MysqlInventoryRepository();
var createInventoryUsecases = new CreateInventoryUseCases_1.CreateInventoryUsecases(database);
var listInventoryUsecases = new ListInventoryUseCases_1.ListInventoryUseCases(database);
var deleteInventoryUsecases = new DeleteInventoryUseCases_1.DeleteInventoryUseCases(database);
exports.createInventoryController = new CreateInventoryController_1.CreateInventoryController(createInventoryUsecases);
exports.listInventoryController = new ListInventoryController_1.ListInventoryController(listInventoryUsecases);
exports.deleteInventoryController = new DeleteInventoryController_1.DeleteInventoryController(deleteInventoryUsecases);
var decreaseSoldStockUseCase = new DecreaseSoldStockUseCases_1.DecreaceSoldProductUseCase(database);
